language: php
php:
    - 7.1
    - 7.2
    - 7.3

install: composer install

script:
    - composer ecs
    - composer phpstan
    - composer tester

notifications:
    email:
        on_success: never
        on_failure: always
